name: tests

on:
  push:
  pull_request:

jobs:
  mocha:
    runs-on: ubuntu-latest
    steps:
      - name: Отримати код репозиторію
        uses: actions/checkout@v4

      - name: Встановити Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Встановити залежності
        run: npm ci

      - name: Запустити модульні тести
        run: npm test
